<a href="https://colab.research.google.com/github/gustavoramos82/estudos-pytorch/blob/main/Estudos_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sobre blibiotecas de redes neurais

As duas principais utilizadas: **tensorflow** e **pytorch**
- apesar de ser mais complicado utilizar, pytorch é mais flexivel

In [12]:
import torch
import numpy as np

## Escalar

In [2]:
escalar = torch.tensor(10) # como é um escalar não tem nnehuma dimensão e shape
escalar

tensor(10)

In [3]:
escalar.ndim

0

In [4]:
escalar.shape

torch.Size([])

In [5]:
escalar.item()

10

## Vetor

nesse caso o vetor ele tem dimensão

In [7]:
vetor = torch.tensor([5,10])
vetor

tensor([ 5, 10])

In [8]:
vetor.ndim

1

In [9]:
vetor.shape

torch.Size([2])

A dimensão armazena os valores, enquanto  o shape diz quantos valores tem na quela dimensão

In [10]:
e1 = torch.tensor(6)
e2 = torch.tensor(8)

vetor_2 = torch.tensor([e1,e2])
vetor_2

tensor([6, 8])

In [13]:
# comparando com o numpy
array = np.array([6,8])
array[0]


np.int64(6)

In [14]:
type(array),type(vetor_2)

(numpy.ndarray, torch.Tensor)

## Matriz

a matriz vai ser um conjunto de vetores

In [15]:
v1 = [5,10]
v2 = [3,16]

matriz = torch.tensor([v1,v2]) # pode construir a matriz mais diretamente
matriz

tensor([[ 5, 10],
        [ 3, 16]])

In [16]:
matriz.ndim

2

In [17]:
matriz.shape

torch.Size([2, 2])

## Tensor

In [18]:
tensor = torch.tensor ([
    [[1,2,3],[7,2,-1]],
    [[-1,5,3],[12,-10,8]]
])

In [19]:
tensor.ndim

3

In [20]:
tensor.shape

torch.Size([2, 2, 3])